---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    serviceType: LoadBalancer
    prometheus:
      service:
        enabled: false
      monitor:
        enabled: false
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.3.99
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    rbac:
      create: true
    isClusterService: false
    servers:
    - zones:
      - zone: robotwizard.co.uk
        scheme: dns://
        use_tcp: false
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      # - name: kubernetes
      #   parameters: cluster.local in-addr.arpa ip6.arpa
      #   configBlock: |-
      #     pods insecure
      #     fallthrough in-addr.arpa ip6.arpa
      #     ttl 30
      # - name: prometheus
      #   parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: file
        parameters: /etc/coredns/robotwizard.co.uk
    zoneFiles:
     - filename: robotwizard.co.uk
       domain: robotwizard.co.uk
       contents: |
         robotwizard.co.uk.   IN SOA ns-1403.awsdns-47.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
         *.robotwizard.co.uk. IN A   10.0.3.150
         robotwizard.co.uk. IN A   10.0.0.1
         test.robotwizard.co.uk. IN A   10.9.9.9
