---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: Secret
    name: external-dns-helm-values
    optional: false
  values:
    image:
      repository: raspbernetes/external-dns
      tag: v0.7.4
    domainFilters: ["robotwizard.co.uk"]
    policy: sync
    aws:
      credentials:
        accessKey: AKIAW4YYMLNFPY4BD76X
    txtPrefix: robotwizard
