---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 10.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1196
    env:
      TZ: "Europe/London"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: sonarr.robotwizard.co.uk
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "sonarr.robotwizard.co.uk"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: nfs-data-pvc
        subPath: sonarr
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: sonarr
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
    - key: "arm"
      operator: "Exists"
    additionalContainers:
    - name: youtubedl
      image: cwlf/sonarr_youtubedl:main
      imagePullPolicy: Always
      volumeMounts:
      - name: config
        mountPath: /config
      - name: media
        mountPath: /sonarr_root
      - name: config
        mountPath: /logs
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k3s-r64-0
