---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ui.robotwizard.co.uk
    http:
      paths:
      - path: /
        backend:
            serviceName: ui
            servicePort: 80
  tls:
  - hosts:
    - ui.robotwizard.co.uk
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - name: http
    port: 80
  type: ExternalName
  externalName: 10.0.1.14
