---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
    retries: 3
  upgrade:
    remediation:
    retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.13
    replicas: 1
    timeZone: "Europe/London"
    config: |
      upstream:
        externalResolvers:
        - tcp+udp:9.9.9.9
        - tcp-tls:dns.quad9.net
        - https://dns.quad9.net/dns-query
      conditional:
        mapping:
          local: tcp+udp:10.0.0.1
          robotwizard.co.uk: tcp+udp:10.0.3.99
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/billimek/k8s-gitops/master/default/blocky/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:10.0.0.1
      prometheus:
        enable: false
        path: /metrics
      httpPort: 4000
      logLevel: info
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    serviceTCP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.3.100
      annotations:
        metallb.universe.tf/allow-shared-ip: blocky
    serviceUDP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.3.100
      annotations:
        metallb.universe.tf/allow-shared-ip: blocky
    serviceMonitor:
      enabled: false
    tolerations:
    - key: "arm"
      operator: "Exists"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi
