apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  storageClassName: data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.1.19
    path: "/k3s/data"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi
