---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: wikijs
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: nicolaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      fsGroup: 911
    image:
      repository: linuxserver/wikijs
      tag: "arm64v8-version-2.5.191"
    env:
      TZ: "Europe/London"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 100.64.0.0/10"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.robotwizard.co.uk/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.robotwizard.co.uk/oauth2/start
      hosts:
        - host: wiki.robotwizard.co.uk
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - wiki.robotwizard.co.uk
    persistence:
      config:
        enabled: true
        storageClass: openebs-hostpath
      data:
        enabled: true
        existingClaim: nfs-data-pvc
