---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.2.9-12-minimal
    env:
      TZ: "Europe/London"
      FLOWS: "flows.json"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.robotwizard.co.uk/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.robotwizard.co.uk/oauth2/start
      hosts:
      - host: node-red.robotwizard.co.uk
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "node-red.robotwizard.co.uk"
    persistence:
      data:
        enabled: true
        existingClaim: nfs-data-pvc
        subPath: node-red
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
